name: cicd

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Download dependencies
        run: npm install --save-dev ava@5.3.1 c8@8.0.1 got@11.8.3
  
      - name: Run tests
        run: npm run test
      
      
